import { useState } from 'react';
import { Search, FileText, Edit, Eye, Plus, Save, X, ChevronUp, ChevronDown, Trash2, Check } from 'lucide-react';

interface ContentPage {
  id: string;
  title: string;
  type: 'terms' | 'privacy' | 'about' | 'faq' | 'disclaimer';
  status: 'published' | 'draft';
  lastUpdated: string;
  version?: string;
  content?: string;
  faqs?: { id: string; question: string; answer: string; enabled: boolean }[];
}

export function ContentPages() {
  const [searchTerm, setSearchTerm] = useState('');
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [selectedPage, setSelectedPage] = useState<ContentPage | null>(null);
  const [editContent, setEditContent] = useState('');
  const [newFaq, setNewFaq] = useState({ question: '', answer: '' });
  const [showAddFaq, setShowAddFaq] = useState(false);

  const [pages, setPages] = useState<ContentPage[]>([
    {
      id: '1',
      title: 'Terms & Conditions',
      type: 'terms',
      status: 'published',
      lastUpdated: '2025-01-15',
      version: 'v2.1',
      content: `App Usage Rules\n\nBy using STYLO.AI, you agree to use the app for personal fashion recommendations only...\n\nUser Eligibility\n\nYou must be at least 13 years old to use this app...\n\nAI-Generated Content Disclaimer\n\nAll outfit recommendations are generated by AI and are advisory in nature...`
    },
    {
      id: '2',
      title: 'Privacy Policy',
      type: 'privacy',
      status: 'published',
      lastUpdated: '2025-01-10',
      version: 'v1.5',
      content: `Data Collection\n\nWe collect email addresses, style preferences, and wardrobe images...\n\nAI Photo Processing\n\nYour uploaded photos are processed by our AI engine to generate outfit recommendations...\n\nStorage & Security\n\nAll data is encrypted and stored securely on our servers...`
    },
    {
      id: '3',
      title: 'About Us',
      type: 'about',
      status: 'published',
      lastUpdated: '2024-12-20',
      content: `Our Mission\n\nSTYLO.AI is revolutionizing personal fashion with AI-powered outfit recommendations...\n\nHow It Works\n\nUpload your wardrobe, get personalized outfit suggestions, and discover new styles...`
    },
    {
      id: '4',
      title: 'FAQ',
      type: 'faq',
      status: 'published',
      lastUpdated: '2025-01-02',
      faqs: [
        { id: 'f1', question: 'How does AI outfit recommendation work?', answer: 'Our AI analyzes your wardrobe items, style preferences, and current trends to suggest outfits that match your taste.', enabled: true },
        { id: 'f2', question: 'Is my photo stored?', answer: 'Yes, your wardrobe photos are securely stored in your account to provide personalized recommendations.', enabled: true },
        { id: 'f3', question: 'Can I delete my wardrobe?', answer: 'Absolutely! You can delete individual items or your entire wardrobe from the app settings.', enabled: true },
        { id: 'f4', question: 'Why am I seeing affiliate products?', answer: 'We show curated product recommendations to help you discover items that match your style. Some may include affiliate links.', enabled: true },
        { id: 'f5', question: 'Is the app free?', answer: 'STYLO.AI offers a free tier with basic features. Premium features are available with a subscription.', enabled: true }
      ]
    },
    {
      id: '5',
      title: 'AI Disclaimer',
      type: 'disclaimer',
      status: 'published',
      lastUpdated: '2024-12-15',
      content: `AI Advisory Notice\n\nAll suggestions provided by STYLO.AI are advisory in nature...\n\nNo Guarantee of Accuracy\n\nWhile we strive for accuracy, AI fashion recommendations may not always align with your preferences...\n\nNo Liability for Purchases\n\nSTYLO.AI is not responsible for purchase decisions made based on our recommendations...`
    }
  ]);

  const handleEditClick = (page: ContentPage) => {
    setSelectedPage(page);
    setEditContent(page.content || '');
    setIsEditDialogOpen(true);
  };

  const handleSave = () => {
    if (selectedPage) {
      setPages(pages.map(p =>
        p.id === selectedPage.id
          ? { ...p, content: editContent, lastUpdated: new Date().toISOString().split('T')[0] }
          : p
      ));
      setIsEditDialogOpen(false);
      setSelectedPage(null);
    }
  };

  const handleToggleStatus = (id: string) => {
    setPages(pages.map(p =>
      p.id === id
        ? { ...p, status: p.status === 'published' ? 'draft' : 'published' }
        : p
    ));
  };

  const handleAddFaq = () => {
    if (selectedPage && newFaq.question && newFaq.answer) {
      const updatedFaqs = [
        ...(selectedPage.faqs || []),
        { id: `f${Date.now()}`, question: newFaq.question, answer: newFaq.answer, enabled: true }
      ];
      setPages(pages.map(p =>
        p.id === selectedPage.id
          ? { ...p, faqs: updatedFaqs, lastUpdated: new Date().toISOString().split('T')[0] }
          : p
      ));
      setSelectedPage({ ...selectedPage, faqs: updatedFaqs });
      setNewFaq({ question: '', answer: '' });
      setShowAddFaq(false);
    }
  };

  const handleDeleteFaq = (faqId: string) => {
    if (selectedPage) {
      const updatedFaqs = selectedPage.faqs?.filter(f => f.id !== faqId) || [];
      setPages(pages.map(p =>
        p.id === selectedPage.id
          ? { ...p, faqs: updatedFaqs, lastUpdated: new Date().toISOString().split('T')[0] }
          : p
      ));
      setSelectedPage({ ...selectedPage, faqs: updatedFaqs });
    }
  };

  const handleToggleFaq = (faqId: string) => {
    if (selectedPage) {
      const updatedFaqs = selectedPage.faqs?.map(f =>
        f.id === faqId ? { ...f, enabled: !f.enabled } : f
      ) || [];
      setPages(pages.map(p =>
        p.id === selectedPage.id
          ? { ...p, faqs: updatedFaqs }
          : p
      ));
      setSelectedPage({ ...selectedPage, faqs: updatedFaqs });
    }
  };

  const handleMoveFaq = (faqId: string, direction: 'up' | 'down') => {
    if (selectedPage && selectedPage.faqs) {
      const index = selectedPage.faqs.findIndex(f => f.id === faqId);
      if (
        (direction === 'up' && index > 0) ||
        (direction === 'down' && index < selectedPage.faqs.length - 1)
      ) {
        const newFaqs = [...selectedPage.faqs];
        const targetIndex = direction === 'up' ? index - 1 : index + 1;
        [newFaqs[index], newFaqs[targetIndex]] = [newFaqs[targetIndex], newFaqs[index]];

        setPages(pages.map(p =>
          p.id === selectedPage.id
            ? { ...p, faqs: newFaqs }
            : p
        ));
        setSelectedPage({ ...selectedPage, faqs: newFaqs });
      }
    }
  };

  const filteredPages = pages.filter(page =>
    page.title.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="flex-1 flex flex-col bg-gray-50 overflow-hidden">
      {/* Header */}
      <div className="bg-white border-b border-gray-100 px-8 py-5 flex items-center justify-between">
        <div>
          <h1 className="text-[20px] tracking-tight mb-1">Content Pages</h1>
          <p className="text-[13px] text-gray-500">Manage app content and legal pages</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" strokeWidth={1.5} />
            <input
              type="text"
              placeholder="Search pages..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9 pr-4 py-2 bg-gray-50 rounded-xl text-[13px] w-[280px] focus:outline-none focus:ring-2 focus:ring-black/5"
            />
          </div>
          <div className="w-9 h-9 bg-black rounded-full flex items-center justify-center">
            <span className="text-white text-xs">AD</span>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-8">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-100">
                  <th className="text-left px-6 py-4 text-[12px] text-gray-500 tracking-wide">PAGE</th>
                  <th className="text-left px-6 py-4 text-[12px] text-gray-500 tracking-wide">TYPE</th>
                  <th className="text-left px-6 py-4 text-[12px] text-gray-500 tracking-wide">STATUS</th>
                  <th className="text-left px-6 py-4 text-[12px] text-gray-500 tracking-wide">VERSION</th>
                  <th className="text-left px-6 py-4 text-[12px] text-gray-500 tracking-wide">LAST UPDATED</th>
                  <th className="text-right px-6 py-4 text-[12px] text-gray-500 tracking-wide">ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {filteredPages.map((page) => (
                  <tr key={page.id} className="border-b border-gray-50 hover:bg-gray-50/50 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center">
                          <FileText className="w-4 h-4 text-gray-600" strokeWidth={1.5} />
                        </div>
                        <span className="text-[14px]">{page.title}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-[13px] text-gray-600 capitalize">{page.type}</span>
                    </td>
                    <td className="px-6 py-4">
                      <button
                        onClick={() => handleToggleStatus(page.id)}
                        className={`px-3 py-1.5 rounded-lg text-[12px] transition-colors ${page.status === 'published'
                            ? 'bg-black text-white'
                            : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                          }`}
                      >
                        {page.status === 'published' ? 'Published' : 'Draft'}
                      </button>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-[13px] text-gray-600">{page.version || '-'}</span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-[13px] text-gray-500">{page.lastUpdated}</span>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center justify-end gap-2">
                        <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                          <Eye className="w-4 h-4 text-gray-400" strokeWidth={1.5} />
                        </button>
                        <button
                          className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                          onClick={() => handleEditClick(page)}
                        >
                          <Edit className="w-4 h-4 text-gray-400 hover:text-black" strokeWidth={1.5} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Edit Dialog */}
      {isEditDialogOpen && selectedPage && (
        <div className="fixed inset-0 backdrop-blur-md bg-white/30 flex items-center justify-center z-50" onClick={() => setIsEditDialogOpen(false)}>
          <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full mx-4 max-h-[90vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
            <div className="p-6 border-b border-gray-100">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-[17px] tracking-tight">Edit {selectedPage.title}</h3>
                  <p className="text-[13px] text-gray-500 mt-1">
                    {selectedPage.type === 'faq' ? 'Manage FAQ items' : 'Update page content'}
                  </p>
                </div>
                <button
                  className="p-2 hover:bg-gray-100 rounded-xl transition-colors"
                  onClick={() => setIsEditDialogOpen(false)}
                >
                  <X className="w-4 h-4 text-gray-400" strokeWidth={1.5} />
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-auto p-6">
              {selectedPage.type === 'faq' ? (
                <div className="space-y-4">
                  {/* Add FAQ Button */}
                  {!showAddFaq && (
                    <button
                      onClick={() => setShowAddFaq(true)}
                      className="w-full px-4 py-3 border-2 border-dashed border-gray-200 rounded-xl hover:border-gray-300 transition-colors flex items-center justify-center gap-2 text-gray-600 text-[14px]"
                    >
                      <Plus className="w-4 h-4" strokeWidth={1.5} />
                      Add New FAQ
                    </button>
                  )}

                  {/* Add FAQ Form */}
                  {showAddFaq && (
                    <div className="bg-gray-50 rounded-xl p-4 space-y-3">
                      <input
                        type="text"
                        placeholder="Question"
                        value={newFaq.question}
                        onChange={(e) => setNewFaq({ ...newFaq, question: e.target.value })}
                        className="w-full px-4 py-2.5 bg-white rounded-lg text-[14px] focus:outline-none focus:ring-2 focus:ring-black/5 border border-gray-200"
                      />
                      <textarea
                        placeholder="Answer"
                        value={newFaq.answer}
                        onChange={(e) => setNewFaq({ ...newFaq, answer: e.target.value })}
                        className="w-full px-4 py-2.5 bg-white rounded-lg text-[14px] focus:outline-none focus:ring-2 focus:ring-black/5 border border-gray-200 min-h-[100px] resize-none"
                      />
                      <div className="flex items-center gap-2">
                        <button
                          onClick={handleAddFaq}
                          className="px-4 py-2 bg-black text-white rounded-lg text-[13px] hover:bg-gray-800 transition-colors"
                        >
                          Add FAQ
                        </button>
                        <button
                          onClick={() => {
                            setShowAddFaq(false);
                            setNewFaq({ question: '', answer: '' });
                          }}
                          className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-[13px] hover:bg-gray-200 transition-colors"
                        >
                          Cancel
                        </button>
                      </div>
                    </div>
                  )}

                  {/* FAQ List */}
                  <div className="space-y-2 mt-4">
                    {selectedPage.faqs?.map((faq, index) => (
                      <div key={faq.id} className={`bg-white rounded-xl p-4 border ${faq.enabled ? 'border-gray-200' : 'border-gray-100 opacity-50'}`}>
                        <div className="flex items-start gap-3">
                          <div className="flex flex-col gap-1 pt-1">
                            <button
                              onClick={() => handleMoveFaq(faq.id, 'up')}
                              disabled={index === 0}
                              className={`p-1 rounded hover:bg-gray-100 transition-colors ${index === 0 ? 'opacity-30 cursor-not-allowed' : ''}`}
                            >
                              <ChevronUp className="w-3 h-3 text-gray-600" strokeWidth={2} />
                            </button>
                            <button
                              onClick={() => handleMoveFaq(faq.id, 'down')}
                              disabled={index === (selectedPage.faqs?.length || 0) - 1}
                              className={`p-1 rounded hover:bg-gray-100 transition-colors ${index === (selectedPage.faqs?.length || 0) - 1 ? 'opacity-30 cursor-not-allowed' : ''}`}
                            >
                              <ChevronDown className="w-3 h-3 text-gray-600" strokeWidth={2} />
                            </button>
                          </div>
                          <div className="flex-1">
                            <div className="text-[14px] mb-2">{faq.question}</div>
                            <div className="text-[13px] text-gray-600">{faq.answer}</div>
                          </div>
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handleToggleFaq(faq.id)}
                              className={`p-2 rounded-lg transition-colors ${faq.enabled ? 'bg-black text-white' : 'bg-gray-100 text-gray-400 hover:bg-gray-200'}`}
                            >
                              <Check className="w-3 h-3" strokeWidth={2} />
                            </button>
                            <button
                              onClick={() => handleDeleteFaq(faq.id)}
                              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                            >
                              <Trash2 className="w-3 h-3 text-gray-400 hover:text-black" strokeWidth={1.5} />
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <div>
                  <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="w-full px-4 py-3 bg-gray-50 rounded-xl text-[14px] focus:outline-none focus:ring-2 focus:ring-black/5 min-h-[400px] resize-none border border-gray-200"
                    placeholder="Enter page content..."
                  />
                  <div className="mt-4 text-[12px] text-gray-400">
                    Use line breaks to separate sections. Support for formatting coming soon.
                  </div>
                </div>
              )}
            </div>

            <div className="p-6 border-t border-gray-100 flex items-center justify-between">
              <div className="text-[13px] text-gray-500">
                Last updated: {selectedPage.lastUpdated}
              </div>
              <div className="flex items-center gap-3">
                <button
                  className="px-5 py-2.5 hover:bg-gray-100 rounded-xl transition-colors text-[14px] text-gray-700"
                  onClick={() => setIsEditDialogOpen(false)}
                >
                  Cancel
                </button>
                {selectedPage.type !== 'faq' && (
                  <button
                    className="px-5 py-2.5 bg-black text-white hover:bg-gray-800 rounded-xl transition-colors text-[14px] flex items-center gap-2"
                    onClick={handleSave}
                  >
                    <Save className="w-4 h-4" strokeWidth={1.5} />
                    Save Changes
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}